# 百度文心一言API配置文件
# 基于 https://luckycola.com.cn/ai/openwxyy 接口
llm:
  api_type: "wenxin"  # 使用百度文心一言API
  base_url: "https://luckycola.com.cn/ai/openwxyy"  # 文心一言API地址
  app_key: "652a1761e95421d67847d086"
  uid: "FUfMOe1697257279052FC0ayVmYAY" 
  is_long_chat: 1  # 是否为长对话，1表示是，0表示否

# 其他配置项已移除，仅保留文心一言API相关配置
repair_llm_output: true  # 当输出不是有效的json时，尝试修复它
